[package]
name = "notification-daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
zbus = { version = "4.4.0", features = [] }
tokio = { version = "1.39.2", features = ["default", "rt", "macros"] }
serde = "1.0.204"